### ISSUE TITLE
Cant install on AUR (missing dependencies not stated in the AUR pkg)

### ISSUE THREAD

**Issue by maplepy** [PabloLec/RecoverPy#360]
**Describe the bug**
Cant install, be sure to include the correct dependencies on the aur package

**To Reproduce**
1. Check the log

**Expected behavior**
install

**System (please complete the following information, either manually or just paste the output of given commands):**
Description:	Arch Linux
Kitty
fish, version 3.7.0

**Additional context**
```
ys grep coreutils util-linux progress --needed 
Sync Dependency (3): util-linux-2.39.3-1, grep-3.11-1, coreutils-9.4-2
Sync Explicit (1): progress-0.17-1
warning: grep-3.11-1 is up to date -- skipping
warning: coreutils-9.4-2 is up to date -- skipping
warning: util-linux-2.39.3-1 is up to date -- skipping
resolving dependencies...
looking for conflicting packages...

Packages (1) progress-0.17-1

Total Download Size:   0.01 MiB
Total Installed Size:  0.03 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 progress-0.17-1-x86_64       13.5 KiB  57.9 KiB/s 00:00 [##############################] 100%
(1/1) checking keys in keyring                           [##############################] 100%
(1/1) checking package integrity                         [##############################] 100%
(1/1) loading package files                              [##############################] 100%
(1/1) checking for file conflicts                        [##############################] 100%
(1/1) checking available disk space                      [##############################] 100%
:: Processing package changes...
(1/1) installing progress                                [##############################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

~ ❯ ys python-recoverpy
AUR Explicit (1): python-recoverpy-2.1.5-1
:: PKGBUILD up to date, skipping download: python-recoverpy
  1 python-recoverpy                 (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
  1 python-recoverpy                 (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: python-recoverpy 2.1.5-1 (Fri 12 Jan 2024 02:48:04 PM CET)
==> Retrieving sources...
  -> Found recoverpy-2.1.5.tar.gz
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    recoverpy-2.1.5.tar.gz ... Passed
:: (1/1) Parsing SRCINFO: python-recoverpy
==> Making package: python-recoverpy 2.1.5-1 (Fri 12 Jan 2024 02:48:05 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found recoverpy-2.1.5.tar.gz
==> Validating source files with sha256sums...
    recoverpy-2.1.5.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting recoverpy-2.1.5.tar.gz with bsdtar
==> Sources are ready.
==> Making package: python-recoverpy 2.1.5-1 (Fri 12 Jan 2024 02:48:06 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
* Getting build dependencies for wheel...

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'poetry'

ERROR Backend 'poetry.core.masonry.api' is not available.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-recoverpy-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python-recoverpy - exit status 4
```

**Comment by maplepy** [comment]
Please put the required dependencies in the `makedepends`

```
pkgbase='python-recoverpy'
pkgname=('python-recoverpy')
_module='recoverpy'
_src_folder='recoverpy-2.1.5'
pkgver='2.1.5'
pkgrel=1
pkgdesc="A TUI to recover overwritten or deleted data."
url="https://github.com/PabloLec/recoverpy"
depends=('python')
makedepends=('python-build' 'python-installer' 'python-wheel')
license=(GNU GPLv3)
arch=('any')
source=("https://files.pythonhosted.org/packages/88/67/7ef7dc81c4be47620adc83b232b7a0ffd992ec312e087bc1f633a0961b1a/recoverpy-2.1.5.tar.gz")
sha256sums=('9a2a831e9945585a54ce968d877dc81983d8228cc2b5c2fbacfff5480d09a393')

build() {
    cd "${srcdir}/${_src_folder}"
    python -m build --wheel --no-isolation
}

package() {
    depends+=()
    cd "${srcdir}/${_src_folder}"
    python -m installer --destdir="${pkgdir}" dist/*.whl
}
```

**Comment by maplepy** [comment]
stuff like `python-poetry`, `grep` `coreutils` `util-linux` `progress` etc.

**Comment by maplepy** [comment]
```
python -m recoverpy                                                                    ✘ 2
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/lib/python3.11/site-packages/recoverpy/__init__.py", line 8, in <module>
    from recoverpy.ui.app import RecoverpyApp
  File "/usr/lib/python3.11/site-packages/recoverpy/ui/app.py", line 6, in <module>
    from textual.app import App
ModuleNotFoundError: No module named 'textual'
```

**Comment by PabloLec** [comment]
Hello and thank you for the issue. I am not an Arch user, and the upload to the AUR was initially suggested by a user, but I see that it's not functional. I attempted a quick fix in a Docker image, but it was unsuccessful, especially due to issues with Python dependencies like Textual. Moreover, Textual is still in beta, and it's important to follow the correct version.  
In short, I will be discontinuing AUR support in the next release. It remains to be seen if someone will want to take on this topic in the future, but it's crucial that any push is done in the CI while respecting Textual's version requirements.

**Comment by maplepy** [comment]
I could maybe look into it so it is done automatically if you want?
